### ISSUE TITLE
Generated imports are changing the order on build / next dev

### ISSUE THREAD

**Issue by Rashair** [tatethurston/nextjs-routes#98]
The order of these 2 import swaps when I run `next dev` and `next build` 
![image](https://user-images.githubusercontent.com/33404585/202892898-58e68b47-ccd3-4769-a942-839b43aeea92.png)

It causes unnecessary changes visible in git repo - is there a way to prevent it?

**Comment by tatethurston** [comment]
Hey @Rashair what tool are you using to reorganize imports? ESLint and prettier are ignored for the generated file.

**Comment by Rashair** [comment]
I don't use anything else than `eslint`. I have a plugin for imports reordering:
`eslintr.yml`:
```yaml
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react-hooks/recommended
  - next
globals: {
  React: true,
  jsdom: true,
  JSX: true,
}

rules:
  quotes: [ "error", "double", { "avoidEscape": true, "allowTemplateLiterals": true } ]
  sort-imports: "off"
  import/order: [
    "warn", {
      "groups": [ "external", "builtin", "object", "type", "index", "sibling", "parent", "internal" ],
      "newlines-between": "always",
      "warnOnUnassignedImports": true,
    } ]
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  react/no-unescaped-entities: [ error, { forbid: [ ">", "}" ] } ]
  react/display-name: "off"
  no-unused-vars: "warn"

```
